### ISSUE TITLE
CustomServer Environment Variable

### ISSUE THREAD

**Issue by LostSoulfly** [samcm/synclounge#174]
I've tried every way I can find to get the env variable for SLServer CUSTOM_SERVER to work.

It's a nightmare just to pass a JSON object correctly. I think there should be more information/details on how to do this properly in the readme. I finally got it to load, but now every time I try to join I get this:
![image](https://user-images.githubusercontent.com/9120519/78413942-bef76180-75e7-11ea-9b47-9677cdfb9964.png)

and I see this in the synclounge logs:
![image](https://user-images.githubusercontent.com/9120519/78413953-ce76aa80-75e7-11ea-84a0-fac394c447a5.png)

Same issue with Vivaldi and Firefox.
Same issue whether using my reverse proxy (caddy with https for both SLServer and SyncLounge) or local IP:ports for all URLs.

```
version: '3.3'
services:
    synclounge:
        container_name: synclounge
        restart: unless-stopped
        ports:
            - '8088:8088'
            - '8089:8089'
        environment:
            DOMAIN: synclounge.server.com
            WEB_ACCESSURL: https://synclounge.server.com
            AUTOJOIN_ENABLED: "true"
            CUSTOM_SERVER: '{ "name": "SyncLounge", "location": "Earth", "url": "https://syncloungeslserver.server.com", "logo": "https://synclounge.server.com/flags/usa.png","image":"https://synclounge.server.com/flags/usa.png" }'
        image: starbix/synclounge
```
